### ISSUE TITLE
Ansible 2.10 Syntax Change

### ISSUE THREAD

**Issue by jasondpereira** [ComplianceAsCode/content#6641] opened 2021-02-24 19:04 UTC
#### Description of problem:
  replace:
    dest: 
should be updated to 
  replace:
    path:

You can refer current 2.10 documentation

https://docs.ansible.com/ansible/latest/collections/ansible/builtin/replace_module.html  

#### Operating System Version:
CentOS 8 Stream

#### Steps to Reproduce:

1. run module using Ansible 2.10
2.
3.
4.

#### Actual Results:
TASK [ansible-role-rhel8-cui : Do not allow users to reuse recent passwords - system-auth (change)] ***
fatal: [###.###.###.### FAILED! => {"changed": false, "msg": "Unsupported parameters for (replace) module: follow Supported parameters include: after, attributes, backup, before, encoding, group, mode, owner, path, regexp, replace, selevel, serole, setype, seuser, unsafe_writes, validate"}

**Comment by ggbecker** [comment] 2021-02-24 23:11
This is actually a duplicate of #6138. `dest` parameter is still supported. The culprit here is `follow` which was already removed in this commit: https://github.com/ComplianceAsCode/content/commit/6bb063948e2ddbc9a482ba9270e484db36d52783

The change is not reflected in the ansible-role-rhel8-cui though, and there is no estimate of when it will be updated.

You can try to build the role yourself after building the content:

`python3 utils/ansible_playbook_to_role.py --build-playbooks-dir ./build/ansible/ --dry-run ./build/ansible_roles`

**Closed by ggbecker** 2021-02-24 23:11 UTC
