### ISSUE TITLE
chronyd_or_ntpd_set_maxpoll doesn't pass on RHEL 8 STIG

### ISSUE THREAD

**Issue by Mab879** [ComplianceAsCode/content#11609] opened 2024-02-19 23:03 UTC
#### Description of problem:
chronyd_or_ntpd_set_maxpoll doesn't pass on RHEL 8 systems.

There appears to be an issue with all of our NTP server rules not playing nicely with each other.

#### SCAP Security Guide Version:
master of 46a432b

#### Operating System Version:
RHEL 8.10

#### Steps to Reproduce:

1. Harden System with STIG profile on RHEL 8
2. Scan System

#### Actual Results:
chronyd_or_ntpd_set_maxpoll - fail

#### Expected Results:
chronyd_or_ntpd_set_maxpoll - pass

#### Additional Information/Debugging Steps:
#11583 looks related.

**Comment by vojtapolasek** [comment] 2024-02-26 14:14
This is observed for RHEL 9 as well.

**Comment by vojtapolasek** [comment] 2024-03-01 09:39
This problem no longer appears since eb2f364ccf6b5cc9eb9a9f100d2fe6b02433951e .

**Comment by mildas** [comment] 2024-03-04 08:42
Double remediation fixes the problem. During first remediation, it passes. But second remediation finds it failing and thus remediates it. After that it passes and seems ok. I will remove the waiver and close the issue, do you agree @vojtapolasek ?

**Comment by vojtapolasek** [comment] 2024-03-04 12:50
I mean... I would be interested why it fails during the second step... do we know that? Do we know what fixes the fail?

**Comment by vojtapolasek** [comment] 2024-03-05 09:41
I can confirm this issue is solved by two remediations. This issue appears in case tha there are no server or pool directives defined in /etc/chrony.conf prior the first remediation.
The issue happens as follows, thanks @comps  for finding it out:
1. Evaluation is performed. The rule chronyd_or_ntpd_set_maxpoll passes because there is no pool or server entry defined. The rule chronyd_specify_remote_server fails because of the same reason.
2. remediation is performed. Only the rule chronyd_specify_remote_server gets remediated because it failed in the previous step. But the rule chronyd_or_ntpd_set_maxpoll starts failing because the remediation of the rule chronyd_specify_remote_server does not include the maxpoll option.
3. Second evaluation and remediation is performed. The rule chronyd_or_ntpd_set_maxpoll is shown as failing and is subsequently remediated. Now it should stabilize.

I think this could be fixed by manipulating rule ordering.

**Closed** 2024-03-05 10:57 UTC
Labels: productization-issue, RHEL9, RHEL8, STIG
