### ISSUE TITLE
Rule sysctl_net_ipv4_conf_all_accept_source_route is misaligned with DISA

### ISSUE THREAD

**Issue by marcusburghardt** [ComplianceAsCode/content#9891] opened 2022-11-28 09:45 UTC
#### Description of problem:
The `sysctl_net_ipv4_conf_all_accept_source_route` rule is misaligned with the `SV-204609r603261_rule` rule from the DISA content in `disa-stig-rhel7-v3r9-xccdf-scap.xml`.

#### SCAP Security Guide Version:
master as of 2022-11-26

#### Operating System Version:
RHEL7.9

#### Steps to Reproduce:
1. Evaluate RHEL 7 STIG profile
2. Evaluate disa-stig-rhel7-v3r9-xccdf-scap.xml

#### Actual Results:
sysctl_net_ipv4_conf_all_accept_source_route : fail
SV-204609r603261_rule : pass

#### Expected Results:
both rules pass

#### Additional Information/Debugging Steps:
This problem occurs also with the "STIG with GUI" profile.

EDIT: The rule results have been corrected, their values were inverted.

**Comment by yuumasato** [comment] 2022-11-29 13:42
@marcusburghardt I cannot reproduce the issue locally.

I was taking a look at the test logs and it seems you misinterpreted the results, our rule is failing and the disa one is passing.

**Comment by yuumasato** [comment] 2022-11-29 13:47
And the rule results in `fail` because the Ansible remediation did not finish correctly.

**Comment by yuumasato** [comment] 2022-11-29 13:50
@marcusburghardt It is not in the ticket but this only happens with Ansible right?

**Comment by marcusburghardt** [comment] 2022-12-07 20:46
> @marcusburghardt It is not in the ticket but this only happens with Ansible right?

Correct.

**Comment by matusmarhefka** [comment] 2022-12-08 10:22
Closing, issue is fixed as of master https://github.com/ComplianceAsCode/content/commit/e7502afdbbfe485f0c566e5d71b02f5bd5c2b7b8.

**Closed by matusmarhefka** 2022-12-08 10:22 UTC
Labels: productization-issue, RHEL7
