### ISSUE TITLE
Ubuntu 22.04 existing sudo being overridden when using --remediate in oscap

### ISSUE THREAD

**Issue by huornlmj** [ComplianceAsCode/content#10760] opened 2023-06-27 14:32 UTC
#### Description of problem:
After running:

```console
$ sudo -E oscap xccdf eval --remediate --profile $profile --results $profile.xml --report $profile.html --oval-results $scap
```
where:
```console
$ echo $scap
/home/user/downloads/scap-security-guide-0.1.68/ssg-ubuntu2204-ds-1.2.xml
$ echo $profile
xccdf_org.ssgproject.content_profile_cis_level2_server
```
My standard sudo-allowed user loses sudo permissions.

#### SCAP Security Guide Version:
0.1.68

#### Operating System Version:
Linux Ubuntu 22.04.2 LTS

#### Steps to Reproduce:

1. Have a standard user with sudo permissions
2. Apply the above profile remediation 
3. Observe that the standard user has now lost sudo permissions
4. No break glass option now available, reinstall OS or boot OS from an alternative source to manually fix the sudoers file

**Comment by dodys** [comment] 2023-06-28 08:18
hey @huornlmj did you get any logs or error messages?
Did you see any difference if you just use `cis_level1_server`?

I will try to reproduce it here in a few minutes, but any information in the meantime will be helpful.

**Comment by huornlmj** [comment] 2023-06-28 08:45
I did some investigation and I found that the line in the /etc/sudoers that was providing the sudo group with sudo permissions had been remarked out by the remediation by OpenSCAP.  I booted the system with a gpated ISO and manually uncommented it and rebooted and my limited user got sudo permissions back.  Is it worth noting that I had lreviously already added the NOPASSWD:ALL to the same line?

**Comment by dodys** [comment] 2023-06-28 08:50
> I did some investigation and I found that the line in the /etc/sudoers that was providing the sudo group with sudo permissions had been remarked out by the remediation by OpenSCAP. I booted the system with a gpated ISO and manually uncommented it and rebooted and my limited user got sudo permissions back. Is it worth noting that I had lreviously already added the NOPASSWD:ALL to the same line?

yes that's helpful, it could be that it is messing up because of some "unexpected" configuration. I will be testing it and proposing a change. Thanks again!

**Comment by dodys** [comment] 2023-06-28 12:56
@huornlmj by "Observe that the standard user has now lost sudo permissions" what do you mean? 
is it asking for sudo password?

**Comment by dodys** [comment] 2023-06-29 07:48
@huornlmj for now we are discussing if we should do something instead during the remediation, but the CIS benchmark specifically mentions:
`Remove any line with occurrences of NOPASSWD tags in the file.`
My recommendation in the meantime is that you use scap-workbench and customize the profile to not include `sudo_require_authentication` if your requirements are to have the NOPASSWD set for the sudo group.

**Comment by marcusburghardt** [comment] 2023-07-03 07:51
This is a valid case, indeed. Regardless of the CIS mention, IMO the relevant rules should care about the line options only, as even mentioned in the rule descriptions. By commenting the entire line where the option is present seems to me more than the necessary to remediate and can also cause disruptions, as described in this issue.

It seems reasonable to me to update the macros used in these rules to remove the undesired options but honor the other configuration parameters in the line.

**Comment by dodys** [comment] 2023-07-19 09:54
> This is a valid case, indeed. Regardless of the CIS mention, IMO the relevant rules should care about the line options only, as even mentioned in the rule descriptions. By commenting the entire line where the option is present seems to me more than the necessary to remediate and can also cause disruptions, as described in this issue.
> 
> It seems reasonable to me to update the macros used in these rules to remove the undesired options but honor the other configuration parameters in the line.

Thanks @marcusburghardt, but I believe that just removing the parameters will create some incorrect configuration lines
for example if I had a line like:
`Defaults:ubuntu !authenticate`
if I just remove the !authenticate that will create a syntax issue, that's why I suggested maybe just replacing the parameter.

**Comment by marcusburghardt** [comment] 2023-07-21 06:26
> > This is a valid case, indeed. Regardless of the CIS mention, IMO the relevant rules should care about the line options only, as even mentioned in the rule descriptions. By commenting the entire line where the option is present seems to me more than the necessary to remediate and can also cause disruptions, as described in this issue.
> > It seems reasonable to me to update the macros used in these rules to remove the undesired options but honor the other configuration parameters in the line.
> 
> Thanks @marcusburghardt, but I believe that just removing the parameters will create some incorrect configuration lines for example if I had a line like: `Defaults:ubuntu !authenticate` if I just remove the !authenticate that will create a syntax issue, that's why I suggested maybe just replacing the parameter.

Hi @dodys , this is also a great and valid example. Now it is much more clear for me the reason of just replacing the parameter by its opposite representation. I agree with you.

**Comment by mpurg** [comment] 2024-12-02 16:43
> My recommendation in the meantime is that you use scap-workbench and customize the profile to not include `sudo_require_authentication` if your requirements are to have the NOPASSWD set for the sudo group.

I agree with this recommendation. Modifying/removing sudoers parameters inline could lead to broken setups (as shown by @dodys), and will also not be aligned with the CIS benchmark.

**Comment by dodys** [comment] 2024-12-02 16:44
Closing this as not planned

**Closed by dodys** 2024-12-02 16:44 UTC
Labels: Ubuntu, CIS
