### ISSUE TITLE
Rule sshd_disable_empty_passwords is misaligned with DISA

### ISSUE THREAD

**Issue by marcusburghardt** [ComplianceAsCode/content#9893] opened 2022-11-28 09:58 UTC
#### Description of problem:
The `sshd_disable_empty_passwords` rule is misaligned with the `SV-204425r603261_rule` rule from the DISA content in `disa-stig-rhel7-v3r9-xccdf-scap.xml`.

#### SCAP Security Guide Version:
master as of 2022-11-26

#### Operating System Version:
RHEL7.9

#### Steps to Reproduce:
1. Remediate a RHEL7 system using the Ansible Playbook from RHEL7 STIG profile
2. Evaluate RHEL 7 STIG profile
3. Evaluate disa-stig-rhel7-v3r9-xccdf-scap.xml

#### Actual Results:
sshd_disable_empty_passwords : fail
SV-204425r603261_rule : pass

#### Expected Results:
both rules pass

#### Additional Information/Debugging Steps:
This problem occurs with Ansible remediation.
This problem occurs also with the "STIG with GUI" profile.

EDIT: The rule results have been corrected, their values were inverted.

**Comment by vojtapolasek** [comment] 2022-11-29 13:00
I can't reproduce this as of commit 74ca327dc3ea0b7c813263d13e230cd62ac70b5a .
I tried this on RHEL 7.9 VM. Do you have any HTML reports / logs which would show the error?

**Comment by yuumasato** [comment] 2022-11-29 13:44
I think Marcus misinterpreted the test results.
Our rule is failing, and the DISA rule is passing.

**Comment by yuumasato** [comment] 2022-11-29 13:47
And the rule results in `fail` because the Ansible remediation did not finish correctly.

**Comment by matusmarhefka** [comment] 2022-12-08 10:25
Closing, issue is fixed as of master https://github.com/ComplianceAsCode/content/commit/e7502afdbbfe485f0c566e5d71b02f5bd5c2b7b8.

**Closed by matusmarhefka** 2022-12-08 10:25 UTC
Labels: Ansible, productization-issue, RHEL7
