### ISSUE TITLE
accounts_password_pam_pwhistory_remember_password_auth is misaligned with DISA

### ISSUE THREAD

**Issue by jan-cerny** [ComplianceAsCode/content#11691] opened 2024-03-13 10:35 UTC
#### Description of problem:
accounts_password_pam_pwhistory_remember_password_auth is misaligned with DISA

#### Details:
The SSG's rule allows to set the remember option also in /etc/security/pwhistory.conf and it prefers this file path.

The DISA's rule requires to set this option directly in /etc/pam.d/password-auth, it doesn't check  /etc/security/pwhistory.conf.

#### Outcome:
SSG result: pass
DISA result: fail

The issue is present in these test variants:
- oscap
- ansible
- anaconda

#### SCAP Security Guide Version:
Current upstream master as of 2024-03-12 as of HEAD cbbca44.

####  External Content's Version:
DISA STIG RHEL 9 V1R1

**Comment by mildas** [comment] 2024-04-08 13:19
Similar to https://github.com/ComplianceAsCode/content/issues/10044 - issue on DISA side. Adding BLOCKED label

**Comment by mildas** [comment] 2024-04-08 13:38
Closing as duplicate of https://github.com/ComplianceAsCode/content/issues/10044

**Closed by mildas** 2024-04-08 13:38 UTC
Labels: productization-issue, RHEL9, STIG, blocked
