### ISSUE TITLE
Rule dconf_gnome_login_banner_text errors with STIG profile

### ISSUE THREAD

**Issue by matusmarhefka** [ComplianceAsCode/content#7850] opened 2021-11-09 13:46 UTC
#### Description of problem:
Rules ~~`banner_etc_issue`~~ (fixed by https://github.com/ComplianceAsCode/content/pull/7842) and `dconf_gnome_login_banner_text` error when remediated using STIG profile on RHEL8 (tested with kickstart installation).

#### SCAP Security Guide Version:
17eed51

#### Operating System Version:
RHEL8

#### Steps to Reproduce:

1. Install RHEL8 with STIG kickstart
2. Scan system with oscap after the install

#### Actual Results:
Rules ~~`banner_etc_issue`~~ and `dconf_gnome_login_banner_text` fail.

#### Expected Results:
Rules ~~`banner_etc_issue`~~ and `dconf_gnome_login_banner_text` pass.

**Comment by Mab879** [comment] 2021-11-09 23:20
Does #7842 fix this issue?

**Comment by matusmarhefka** [comment] 2021-11-10 11:46
> Does #7842 fix this issue?

Yes, it resolved the issue for `banner_etc_issue`, but the `dconf_gnome_login_banner_text` still errors.

**Comment by Mab879** [comment] 2021-11-10 21:14
Possible fix in #7861

**Comment by Mab879** [comment] 2021-11-12 17:44
Possible duplicate of #7463

**Comment by yuumasato** [comment] 2021-11-15 09:50
Closing, reopen if issue still persists.

**Closed by yuumasato** 2021-11-15 09:50 UTC
Labels: productization-issue
