### ISSUE TITLE
timer_dnf-automatic_enabled fails when remediated through Ansible

### ISSUE THREAD

**Issue by vojtapolasek** [ComplianceAsCode/content#12234] opened 2024-07-29 15:21 UTC
#### Description of problem:

The issue seems very similar to this one, but it is about Ansible: https://github.com/ComplianceAsCode/content/issues/12119

#### SCAP Security Guide Version:

master as of d9086f6c3f5d1392e1116486d5a5208c8cba7f8d

#### Operating System Version:

RHEL 9.0, ppc64le

#### Steps to Reproduce:

1. build the content
2. remediate with the ansible playbook of the CUI profile
3. scan the system with oscap

#### Actual Results:

The rule is remediated successfully (it seems) but in the final scan it is shown as failing.

#### Expected Results:

The rule is passing in the final scan.

**Comment by Mab879** [comment] 2024-07-29 20:10
If this is the same issue as #12112, this is not our issue.

**Comment by mildas** [comment] 2024-07-30 12:36
> If this is the same issue as https://github.com/ComplianceAsCode/content/pull/12112, this is not our issue.

Wrong link?

**Comment by Mab879** [comment] 2024-07-30 12:38
Sorry, that should have been #12119, edited as such

**Comment by jan-cerny** [comment] 2024-08-05 11:30
The issue is a duplicate of https://github.com/ComplianceAsCode/content/issues/12119, that one was about Ansible as well. We will close this one for the same reason as that issue: The remediation is correct. After some time, the timer gets activated. So the problem is a time delay.

**Closed by jan-cerny** 2024-08-05 11:30 UTC
Labels: productization-issue
