### ISSUE TITLE
Rule audit_rules_privileged_commands_kmod is misaligned with DISA

### ISSUE THREAD

**Issue by mildas** [ComplianceAsCode/content#9831] opened 2022-11-16 11:12 UTC
#### Description of problem:
SSG content passes, but DISA contet fails. Looking at arf results:
SSG content resulted as true for `audit augenrules kmod` for pattern in `/etc/audit/rules.d/module-change.rules` file
```
^[\s]*-w[\s]+/usr/bin/kmod[\s]+-p[\s]+x[\s]+-F[\s]+auid!=(?:4294967295|unset|-1)[\s]+(-k[\s]+|-F[\s]+key=)[\S]+[\s]*$
```

However, DISA content results in false for `audit augenrules kmod` for pattern in path `/etc/audit/rules.d` for `.*\.rules$` files
```
^\s*-a\s+(always,exit|exit,always)\s+-F\s+path=\/usr\/bin\/kmod\s+(-F\s+perm=([rwa]*x[rwa]*)\s+)?-F\s+auid>=1000\s+-F\s+auid!=(4294967295|-1|unset)(\s+(-k\s+|-F\s+key=)\S+)?\s*$`
```

#### SCAP Security Guide Version:
b609bf6

#### Operating System Version:
RHEL 7.9

#### Steps to Reproduce:
1. Install machine hardened with STIG with GUI
2. Scan using SSG content and using DISA content

#### Actual Results:
Results are misaligned

#### Expected Results:
Results are aligned

**Comment by marcusburghardt** [comment] 2022-11-21 10:01
@yuumasato , since you are involved with the #9824 , would it make sense to assign this issue to you?

**Comment by marcusburghardt** [comment] 2022-11-22 13:28
I believe the #9824 will fix this issue.

**Comment by yuumasato** [comment] 2022-11-24 13:09
> I believe the #9824 will fix this issue.

I believe so too, will close this.
Re-open if the issue is still manifesting.

**Closed by yuumasato** 2022-11-24 13:09 UTC
Labels: productization-issue, RHEL7, STIG
