### ISSUE TITLE
`xccdf_org.ssgproject.content_rule_file_permissions_home_dirs` should it check for world write?

### ISSUE THREAD

**Issue by jcpunk** [ComplianceAsCode/content#7890] opened 2021-11-16 21:13 UTC
#### Description of problem:

Should the check `xccdf_org.ssgproject.content_rule_file_permissions_home_dirs` ([Ensure that User Home Directories are not Group-Writable or World-Readable](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/accounts/accounts-session/file_permissions_home_dirs/rule.yml)) also check if the home area is world writable?  It seems an odd oversight.

A home area of `751` is suitable for my environment.

#### SCAP Security Guide Version:
scap-security-guide-0.1.58-1.fc35.noarch

#### Operating System Version:
Fedora 35

#### Steps to Reproduce:

1. `useradd -m exampleuser`
2. `chmod 753 /home/exampleuser`
3. Run rule `xccdf_org.ssgproject.content_rule_file_permissions_home_dirs`
4.

#### Actual Results:
`/home/exampleuser` meets the requirements of this rule

#### Expected Results:
An error that the directory permits group write.

**Comment by Mab879** [comment] 2021-11-19 16:35
@marcusburghardt do some insight here? Also, we two rules that seem very similar, `file_permissions_home_directories` and `file_permissions_home_dirs`.

**Comment by lenox-joseph** [comment] 2021-11-22 19:48
The rationale for the rule says that people shouldn't be able to write to other people's home directories.

**Comment by marcusburghardt** [comment] 2021-12-02 13:46
Hi @jcpunk , there is actually two very similar rules:
- [file_permissions_home_dirs
](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/accounts/accounts-session/file_permissions_home_dirs/rule.yml)
- [file_permissions_home_directories](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/accounts/accounts-session/file_permissions_home_directories/rule.yml)

The last is present in the current current versions of CIS and STIG benchmarks for RHEL8, for instance. I didn't check other distros, but it is possible that the first rule is outdated in favor of the second one. Could you inform which benchmark are you using, please?

Anyways, if any benchmark still recommends this rule as it is currently described, we have to fix it.
The current logic of the rule `file_permissions_home_dirs`, is checking for expected permissions instead of not expected permissions, like the `file_permissions_home_directories` rule correctly do, and this is causing this wrong result that you described.

**Comment by jcpunk** [comment] 2021-12-02 14:26
Hello,

I'm using the "Standard System Security Profile for $release" with some tailoring.  Some of my target hosts are using apache's mod_userdir.  It is easier to have the home area set to 751 than whip up a rule that only checks on some hosts is there is a posix acl permitting user `apache` execute on the dir.

Hopefully that makes sense,

Pat

**Comment by marcusburghardt** [comment] 2021-12-06 11:43
Hi @jcpunk , today I had an opportunity to better check this rule and I couldn't reproduce the issue you mentioned here.
Actually, the rule resulted in `fail` even with `751`. I also examined the OVAL related to this rule and it is expected that no permission exists for `others`.

I also checked the references informed in this rule and didn't find any information stating about the `exec` permission for `others`.

In this case, I should close this issue since it can't be reproduced and no documentation was found to justify any change (accept `exec` permission) in this rule.
 
I afraid that in your tailored file you can't use neither of the rules I mentioned in my previous comment. In addition, I would recommend you to use `file_permissions_home_directories` instead of `file_permissions_home_dirs` for testing permissions of home directories related to interactive users since this rule is referenced in different benchmarks.

**Comment by jcpunk** [comment] 2021-12-07 14:53
That makes sense.  The `title` should probably be updated to note the expectation that there will be no `other` permissions rather than just no world read.

**Comment by marcusburghardt** [comment] 2021-12-10 09:17
Since I didn't find any current benchmark linked to this rule, to actually validate the context, I would prefer to not change it. It is possible this rule is somehow still used by someone.

Whenever possible, I would recommend the use of the `file_permissions_home_directories` instead.

**Closed by marcusburghardt** 2021-12-10 09:18 UTC
