### ISSUE TITLE
Rules contain wrong package name in STIG fields

### ISSUE THREAD

**Issue by jan-cerny** [ComplianceAsCode/content#9916] opened 2022-12-01 12:56 UTC
#### Description of problem:
During review of #9910  we have discovered that the `policy_specific_content` key might contain wrong values in its subkeys values.

For example, when we build RHEL 7 content and we open the internal resolved file `build/rhel7/rules/install_smartcard_packages.yml`, most of the items contain the correct RHEL 7 package name `pam_pkcs11`. But the `policy_specific_content` contains `openssl-pkcs11` in `checktext` and `fixtext`, and which  `openssl-pkcs11` isn't the correct package name. 

#### SCAP Security Guide Version:
current upstream master as of 2022-12-01 as of HEAD 0e9c45310a83c0e04cae878f698ede8c04cac604

#### Operating System Version:
F 37

#### Steps to Reproduce:

1. ./build_product -d rhel7
2. cat build/rhel7/rules/install_smartcard_packages.yml

#### Actual Results:
openssl-pkcs11 in policy_specific_content

#### Expected Results:
pam_pkcs11 in policy_specific_content

#### Additional Information/Debugging Steps:

There was an issue with the other keys as well (see https://github.com/ComplianceAsCode/content/issues/9894 ) that manifested only when built with Python 2. But that issue seems to be caused by different thing. Our issue doesn't depend on Python version.

**Comment by Mab879** [comment] 2022-12-01 13:25
So the `policy_specific_content` does not use variables currently. That is by design, as it makes it easier to import the changes from the spreadsheet to the repo. However, it does seem to be causing some unintended consequences, as shown here. We do have the ability to create override files like `rhel7.yml`.

**Comment by matejak** [comment] 2022-12-02 09:42
You can see the content here: https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/install_smartcard_packages/policy/stig/shared.yml

Therefore, mystery is solved - it's all literal strings. So I take the "infrastructure" label out, but is it a STIG issue? I feel that in these cases, we should have OS-specific STIG files s.a. the mentioned `rhel7.yml`, because the policy specific content is propagated to the compiled rule, and RHEL7 STIG content somehow contradicts the let's say RHEL8 rule.

**Comment by Mab879** [comment] 2024-12-19 14:22
RHEL 7 is no longer supported this project, closing.

**Closed by Mab879** 2024-12-19 14:22 UTC
Labels: STIG
