### ISSUE TITLE
Bash Jinja macro for line in file does not add CCE placeholder ("@CCENUM@")

### ISSUE THREAD

**Issue by ggbecker** [ComplianceAsCode/content#5608] opened 2020-04-16 09:14 UTC
#### Description of problem:
The bash jinja macro called [`set_config_file`](https://github.com/ComplianceAsCode/content/blob/master/shared/macros-bash.jinja#L402) which was developed to replace the bash function [`replace_or_append.sh`](https://github.com/ComplianceAsCode/content/blob/master/shared/bash_remediation_functions/replace_or_append.sh#L29) does not add information about the CCE identifier as a comment when the remediation detects no previous configuration in the target configuration file (if the configuration is there but just with a wrong value, then it doesn't include this comment, per: [`replace_or_append.sh:70`](https://github.com/ComplianceAsCode/content/blob/master/shared/bash_remediation_functions/replace_or_append.sh#L70))

This feature is only present in bash remediation through the function [`replace_or_append`](https://github.com/ComplianceAsCode/content/blob/master/shared/bash_remediation_functions/replace_or_append.sh#L29). No other remediation type or function implements such feature.

#### SCAP Security Guide Version:
0.1.49

#### Addition Information/Debugging Steps:
The placeholder (`@CCENUM@`) is substituted by the following XSLT transformation: [`xccdf-addremediations.xslt:69`](https://github.com/ComplianceAsCode/content/blob/master/shared/transforms/xccdf-addremediations.xslt#L69)

Relates to: #5599

**Comment by matejak** [comment] 2020-04-16 10:09
As noted in the description, the original feature is incomplete, and therefore inconsistent: Some remediations add CCE comments, while some don't, and the remediation function itself assumes that a comment is always a line that begins with hash, which may not be correct in a general "replace" case.
In addition, this increases the footprint of the remediation, which is not something that should be done without even a basic cost-benefit analysis.
I see the benefit of marking added lines or config files, but only if it is a robust solution with additional benefits. I am not in favor to reintroduce the approach that we had for reasons specified above.

**Comment by vojtapolasek** [comment] 2020-04-16 12:52
I am also against reintroducing this for Bash remediations. We might encounter problems caused by fact that this is implemented for Bash remediations only. We have several cases where we check contents of the whole file, especially with Audit rules. I see several problems here:
- bash remediations would add the comment, Ansible would not. It would complicate the checking.
- The oval check would depend on CCE value, making the check again complicated as CCEs may be added for various platforms etc.

**Comment by Mab879** [comment] 2024-11-07 14:29
Based @vojtapolasek comment closing.

**Closed by Mab879** 2024-11-07 14:29 UTC
Labels: Bash
