### ISSUE TITLE
PCI-DSS profile on RHEL7/RHEL8 - many failing test scenarios

### ISSUE THREAD

**Issue by mildas** [ComplianceAsCode/content#5213] opened 2020-03-03 10:06 UTC
#### Description of problem:
Many test scenarios are failing during the initial stage in the PCI-DSS profile.

It can be caused by incorrect test scenarios or by incorrect OVAL checks.

#### SCAP Security Guide Version:
6ba3fcf

#### Operating System Version:
RHEL 8

#### Steps to Reproduce:

1. `python3 tests/test_suite.py combined --libvirt qemu:///system test_suite_vm                 --datastream /usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml --mode online --remediate-using bash                 xccdf_org.ssgproject.content_profile_pci-dss`

#### Actual Results:
Output from test suite (passed test scenarios, failed test scenarios during the final stage and irrelevant information have been removed from output):

RHEL7
**xccdf_org.ssgproject.content_rule_smartcard_auth**
ERROR - Script installed_enabled.pass.sh using profile (all) found issue:
ERROR - Rule evaluation resulted in fail, instead of expected pass during initial stage 
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_smartcard_auth'.

RHEL8
**xccdf_org.ssgproject.content_rule_ensure_logrotate_activated**
ERROR - Script logrotate_conf_extra_monthly.fail.sh using profile (all) found issue:
ERROR - Rule evaluation resulted in pass, instead of expected fail during initial stage 
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_ensure_logrotate_activated'.

RHEL7/RHEL8
**xccdf_org.ssgproject.content_rule_file_permissions_etc_group**
ERROR - Script narrow_permissions.pass.sh using profile (all) found issue:
ERROR - Rule evaluation resulted in fail, instead of expected pass during initial stage 
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_file_permissions_etc_group'.

RHEL7/RHEL8
**xccdf_org.ssgproject.content_rule_file_permissions_etc_passwd**
ERROR - Script narrow_permissions.pass.sh using profile (all) found issue:
ERROR - Rule evaluation resulted in fail, instead of expected pass during initial stage 
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_file_permissions_etc_passwd'.

#### Expected Results:
Test scenarios pass during the initial stage.

**Comment by vojtapolasek** [comment] 2020-03-03 15:03
For the rule account_disable_post_pw_expiration the problem is that the scenario which should fail uses a value which is correct in scope of pci-dss profile

**Comment by vojtapolasek** [comment] 2020-03-03 15:33
Concerning configure_crypto_policy this is a bit complicated as different profiles expect different cryptopolicies, it needs to be somehow indicated in scenarios which scenario to use when.

**Comment by mildas** [comment] 2020-03-04 08:46
I know about `configure_crypto_policy`. This one is complicated to test because it requires a restart for applying a crypto policy to a system. It will fail until there will be an option to restart a machine after performing test scenario.

About `account_disable_post_pw_expiration` - that's also known problem when one test scenario is being performed on different profiles and each profile has a different expected value. But can it be solved with changing the value in the test scenario so the value is correct/incorrect for both profiles and the expected result is the same for all profiles?

**Comment by vojtapolasek** [comment] 2020-03-04 08:50
The first rule is fixed in
https://github.com/ComplianceAsCode/content/pull/5214

**Comment by mildas** [comment] 2021-03-11 09:24
The `rpm_verify_permissions` test was fixed in #6671

**Closed** 2021-03-15 10:26 UTC
Labels: productization-issue
