### ISSUE TITLE
Playbook stops at TASK [Ensure NetworkManager is installed]

### ISSUE THREAD

**Issue by PiRomant** [ComplianceAsCode/content#12031] opened 2024-05-28 09:36 UTC
#### Description of problem:
Ansible Playbook for CIS Ubuntu 22.04 Level 1 Server Benchmark stops at `TASK [Ensure NetworkManager is installed] `

#### SCAP Security Guide Version:
Profile ID:  xccdf_org.ssgproject.content_profile_cis_level1_server
Benchmark ID:  xccdf_org.ssgproject.content_benchmark_UBUNTU_22-04
Benchmark Version:  0.1.73
XCCDF Version:  1.2

#### Operating System Version:
Ubuntu 22.04.4 LTS

#### Steps to Reproduce:

Use ansible playbook ubuntu2204-playbook-cis_level1_server.yml

#### Actual Results:
```bash
TASK [Ensure NetworkManager is installed] ********************************************************
failed: [192.168.0.1] (item=NetworkManager) => {"ansible_loop_var": "item", "changed": false, "item": "NetworkManager", "msg": "No package matching 'NetworkManager' is available"}

PLAY RECAP ***************************************************************************************
192.168.0.1           : ok=228  changed=69   unreachable=0    failed=1    skipped=32   rescued=0    ignored=0 
```

#### Additional Information/Debugging Steps:
```
ansible-playbook [core 2.14.14]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /bin/ansible-playbook
  python version = 3.9.18 (main, Jan 24 2024, 00:00:00) [GCC 11.4.1 20231218 (Red Hat 11.4.1-3)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

**Comment by ggbecker** [comment] 2024-05-28 09:51
This file needs to be changed: https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/network/network-wireless/wireless_software/wireless_disable_interfaces/ansible/shared.yml#L35

It has NetworkManager hardcoded and maybe for Ubuntu the name of the package is different

**Comment by PiRomant** [comment] 2024-05-30 06:45
Or shouldn't use `network-manager` at all.
https://github.com/ComplianceAsCode/content/issues/11904

**Comment by dodys** [comment] 2024-08-02 06:22
Closing this since it is a duplicate of #11904

**Closed by dodys** 2024-08-02 06:22 UTC
Labels: Ubuntu
