### ISSUE TITLE
Many rules are returning 255 for test scenario scripts

### ISSUE THREAD

**Issue by marcusburghardt** [ComplianceAsCode/content#8914] opened 2022-06-08 08:51 UTC
#### Description of problem:

During the tests with the OSPP profile it was reported many `sysctl` related rules returning `255` after execution of test scenario scripts.

#### SCAP Security Guide Version:

master

#### Operating System Version:

RHEL8

#### Actual Results:

```
ERROR - Rule 'sysctl_net_ipv4_conf_default_rp_filter' test setup script 'correct_value.pass.sh' failed with exit code 255
ERROR - Environment failed to prepare, skipping test
ERROR - Rule 'sysctl_net_ipv4_conf_default_rp_filter' test setup script 'line_not_there.fail.sh' failed with exit code 255
ERROR - Environment failed to prepare, skipping test
ERROR - Rule 'sysctl_net_ipv4_conf_default_rp_filter' test setup script 'wrong_runtime.fail.sh' failed with exit code 255
ERROR - Environment failed to prepare, skipping test
ERROR - Rule 'sysctl_net_ipv4_conf_default_rp_filter' test setup script 'wrong_value.fail.sh' failed with exit code 255
ERROR - Environment failed to prepare, skipping test
```
#### Expected Results:

It is expected the environments are correctly prepared for the assessments.

#### Additional Information/Debugging Steps:

The following scripts are returning 255:
- comment.fail.sh
- correct_value.pass.sh
- line_not_there.fail.sh
- wrong_runtime.fail.sh
- wrong_value.fail.sh
- one_sysctl_conf_one_sysctl_d.fail.sh
- symlink_different_option.pass.sh
- symlink_repeated_sysctl_conf.pass.sh
- symlink_root_duplicate.fail.sh
- symlink_root_incompliant.fail.sh
- symlink_same_option.fail.sh
- symlinks_to_same_file.pass.sh
- two_sysctls_on_d.fail.sh
- two_sysctls_on_same_file.pass.sh
- two_sysctls_on_same_file_name.fail.sh
- wrong_value_run_sysctl_d.fail.sh

**Comment by marcusburghardt** [comment] 2022-06-08 20:43
It reported in many rules from the `ospp` profile.

This is the command I get from the logs where the errors appeared:
`test_suite.py combined --slice 2 3 --libvirt qemu:///system test_suite_vm --datastream /usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml --mode online --remediate-using bash --duplicate-templates --no-reports xccdf_org.ssgproject.content_profile_ospp'`

One of the rules I mentioned in the description and could be used as example: `sysctl_net_ipv4_conf_default_rp_filter`
Let me know if you need more information about the test.

This meantime I can also try to run it again to confirm if it was a temporary problem with the test environment.

**Comment by yuumasato** [comment] 2022-06-09 06:56
Rule `sysctl_net_ipv4_conf_default_rp_filter` is working fine for me too.

**Comment by yuumasato** [comment] 2022-06-09 08:00
So I have run the following and don't get any errors on my local VM.
`python3 tests/test_suite.py combined --slice 2 3 --libvirt qemu:///session rhel86 --datastream build/ssg-rhel8-ds.xml --duplicate-templates xccdf_org.ssgproject.content_profile_ospp`

Looking at the logs I see that the first test scenario of each rule is executed correctly, but any subsequent test scenario fails with `No route to host`.
```
  1 ##### sysctl_net_ipv4_conf_all_secure_redirects / comment.fail.sh #####
  2 ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentityFile=/root/.ssh/ssg_id_ecdsa root@192.168.122.236 cd /root/ssgts/sysctl_net_ipv4_conf_all_secure_redirects; SHARED=/root/ssgts/shared bash -x comment.fail.sh
  3 STDOUT: net.ipv4.conf.all.secure_redirects = 0                                          
  4 STDERR: Warning: Permanently added '192.168.122.236' (ECDSA) to the list of known hosts.                                                                  
  5 + grep -q '^net.ipv4.conf.all.secure_redirects' /etc/sysctl.conf
  6 + echo '# net.ipv4.conf.all.secure_redirects = 0'
  7 + sysctl -w net.ipv4.conf.all.secure_redirects=0
  8 ##### sysctl_net_ipv4_conf_all_secure_redirects / correct_value.pass.sh #####
  9 ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentityFile=/root/.ssh/ssg_id_ecdsa root@192.168.122.236 cd /root/ssgts/sysctl_net_ipv4_conf_all_secure_redirects; SHARED=/root/ssgts/shared bash -x correct_value.pass.sh
 10 STDERR: ssh: connect to host 192.168.122.236 port 22: No route to host
 11 ##### sysctl_net_ipv4_conf_all_secure_redirects / line_not_there.fail.sh #####
 12 ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentityFile=/root/.ssh/ssg_id_ecdsa root@192.168.122.236 cd /root/ssgts/sysctl_net_ipv4_conf_all_secure_redirects; SHARED=/root/ssgts/shared bash -x line_not_there.fail.sh
 13 STDERR: ssh: connect to host 192.168.122.236 port 22: No route to host
 14 ##### sysctl_net_ipv4_conf_all_secure_redirects / wrong_value.fail.sh #####
 15 ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentityFile=/root/.ssh/ssg_id_ecdsa root@192.168.122.236 cd /root/ssgts/sysctl_net_ipv4_conf_all_secure_redirects; SHARED=/root/ssgts/shared bash -x wrong_value.fail.sh
 16 STDERR: ssh: connect to host 192.168.122.236 port 22: No route to host                                                                             
```

I'm this is not related to the test scenarios, but something in the environment.
@mildas Maybe you know what is going on?

**Comment by mildas** [comment] 2022-06-09 16:06
First time seeing that. No idea what's wrong. I wasn't able to reproduce it even on the exactly same RHEL8 compose where the issue occurred.

It seems it's test environment failure, because I see same issue also in audit or in grub2 test scenarios.

For now, don't close the issue and we will get back to it next week during next test run. If the issue not there anymore, we will close it. Otherwise, more investigations.

**Comment by yuumasato** [comment] 2022-06-21 07:52
I'm running into this locally, but only when testing a RHEL7 VM.
Tests on RHEL8 VM work normally.

I think this might be a libvirt issue, while Automatus was struggling to connect to the VM, I issued in a new terminal an ssh command to the VM, and got the same `No route to host error`.

**Comment by mildas** [comment] 2022-07-07 13:12
Did #9015 solved it? Can we close it?

**Comment by yuumasato** [comment] 2022-07-08 08:28
I have not seen this issue in this week's productization, closing.

**Closed by yuumasato** 2022-07-08 08:28 UTC
Labels: productization-issue
