### ISSUE TITLE
Verification of permissions on SSH Server files

### ISSUE THREAD

**Issue by konstruktoid** [ComplianceAsCode/content#3525] opened 2018-10-10 08:22 UTC
#### Description of problem:

`xccdf_org.ssgproject.content_rule_file_permissions_sshd_pub_key` and `xccdf_org.ssgproject.content_rule_file_permissions_sshd_private_key` fails and recommends `$ sudo chmod 0640 /etc/ssh/*_key` and `$ sudo chmod 0644 /etc/ssh/*.pub` to properly set the permissions.

Checking the files on the server verifies that the permissions is already correct.

```
$ stat -c "%A %a %n (%z)" /etc/ssh/*.pub /etc/ssh/*_key /etc/shadow /etc/passwd && LANG=C date
-rw-r--r-- 644 /etc/ssh/ssh_host_ecdsa_key.pub (2018-10-10 10:19:10.448183586 +0200) # manual chmod 0644
-rw-r--r-- 644 /etc/ssh/ssh_host_ed25519_key.pub (2018-04-03 14:58:26.219257987 +0200)
-rw-r--r-- 644 /etc/ssh/ssh_host_rsa_key.pub (2018-04-03 14:58:26.112257985 +0200)
-rw-r----- 640 /etc/ssh/ssh_host_ecdsa_key (2018-04-03 14:58:26.169257986 +0200)
-rw-r----- 640 /etc/ssh/ssh_host_ed25519_key (2018-04-03 14:58:26.219257987 +0200)
-rw-r----- 640 /etc/ssh/ssh_host_rsa_key (2018-04-03 14:58:26.111257985 +0200)
---------- 0 /etc/shadow (2018-10-09 15:32:34.448786230 +0200)
-rw-r--r-- 644 /etc/passwd (2018-10-09 15:32:34.403786063 +0200)
Wed Oct 10 10:20:09 CEST 2018
```

#### SCAP Security Guide Version:

```
openscap-1.2.16-8.el7_5.x86_64
scap-security-guide-doc-0.1.40-2.el7.noarch
scap-security-guide-0.1.40-2.el7.noarch
openscap-scanner-1.2.16-8.el7_5.x86_64
```

#### Operating System Version:

`Red Hat Enterprise Linux Server release 7.5 (Maipo)`

#### Steps to Reproduce:

1. `sudo oscap xccdf eval --fetch-remote-resources --profile xccdf_org.ssgproject.content_profile_stig-rhel7-disa --results-arf rhel7_stig-arf.xml --report rhel7_stig-report.html /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml`

**Comment by jan-cerny** [comment] 2018-10-10 09:35
I believe this has been fixed in https://github.com/ComplianceAsCode/content/pull/3362

**Comment by konstruktoid** [comment] 2018-10-11 06:43
Updated to `scap-security-guide-0.1.41-1.el7.noarch` from https://copr.fedorainfracloud.org/coprs/openscapmaint/openscap-latest/package/scap-security-guide/ and still got the same result.

```
$ grep -E 'product_version|*.pub has mode|_key has mode' /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml
        <ns2:product_version>ssg: [0, 1, 41], python: 2.7.5</ns2:product_version>
            <oval:description>This test makes sure that /etc/ssh/*_key has mode 0640.
            <oval:description>This test makes sure that /etc/ssh/*.pub has mode 0644.
        <ns0:product_version>ssg: 0.1.41</ns0:product_version>
        <ns2:product_version>ssg: [0, 1, 41], python: 2.7.5</ns2:product_version>
        <ns2:product_version>ssg: [0, 1, 41], python: 2.7.5</ns2:product_version>
            <oval:description>This test makes sure that /etc/ssh/*_key has mode 0640.
            <oval:description>This test makes sure that /etc/ssh/*.pub has mode 0644.
        <ns0:product_version>ssg: 0.1.41</ns0:product_version>
$ rpm -ql scap-security-guide | grep 'ssg-rhel7-ds.xml'
/usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml
[tabd@tmongo01 ~]$ rpm -qa | grep scap-
scap-security-guide-0.1.41-1.el7.noarch
openscap-1.2.16-8.el7_5.x86_64
scap-security-guide-doc-0.1.41-1.el7.noarch
openscap-scanner-1.2.16-8.el7_5.x86_64
$
```

**Comment by jan-cerny** [comment] 2018-10-11 08:35
@konstruktoid  You're right, it is not fixed. Thank you very much.

The problem is not in permissions value, but in the file path.
The file paths are handled wrong in our templating system.

See the CSV file:
https://github.com/ComplianceAsCode/content/blob/cbd2d5225469aca753845b3c445ad4f3b4eba1cd/rhel7/templates/csv/file_dir_permissions.csv#L8-L9
It contains an unix glob expression `*_key`.

This glob gets translated into OVAL file object. The result that we ship looks like this:
```
23670         <ns4:file_object comment="/etc/ssh/*_key" id="oval:ssg-object_file_permissions_sshd_private_key:obj:1" version="1">
23671           <ns4:path>/etc/ssh</ns4:path>
23672           <ns4:filename>*_key</ns4:filename>
23673         </ns4:file_object>
```


But, OVAL doesn't support globs. It understands the `filename` literally, as a exact file name. That means it specifies looks for file that has an asterisk in its name. No such file exists there, so the scanner reports a fail.

Instead, there should be a PCRE regular expression and `operation` attribute. It should look like this:
```
23672           <ns4:filename operation="pattern match">^.*_key$</ns4:filename>
```

We have to:
* Fix our template and templating system to support glob or regexes
* Make sure remediations are not broken as well
* Add a test to SSG test suite to prevent similar problems in future.


This problem also affects multiple other rules in multiple products, eg. rules related to httpd.

**Closed as completed** 2018-11-23 08:51 UTC
Labels: BLOCKER
