### ISSUE TITLE
Building OCP4 on Ubuntu 20.10 with OpenSCAP 1.2

### ISSUE THREAD

**Issue by cipherboy** [ComplianceAsCode/content#6798] opened 2021-04-06 15:43 UTC
#### Description of problem:

`master` build fails with:

```
[243/907] [ocp4-content] generating ssg-ocp4-xccdf.xml
FAILED: ssg-ocp4-xccdf.xml 
cd /home/cipherboy/GitHub/cipherboy/scap-security-guide/build/ocp4 && /usr/bin/xsltproc --output /home/cipherboy/GitHub/cipherboy/scap-security-guide/build/ssg-ocp4-xccdf.xml /home/cipherboy/GitHub/cipherboy/scap-security-guide/shared/transforms/shared_xccdf-removeaux.xslt /home/cipherboy/GitHub/cipherboy/scap-security-guide/build/ocp4/xccdf-linked.xml && /usr/bin/sed -i s/oval-linked.xml/ssg-ocp4-oval.xml/g /home/cipherboy/GitHub/cipherboy/scap-security-guide/build/ssg-ocp4-xccdf.xml && /usr/bin/sed -i s/ocil-linked.xml/ssg-ocp4-ocil.xml/g /home/cipherboy/GitHub/cipherboy/scap-security-guide/build/ssg-ocp4-xccdf.xml && env PYTHONPATH=/home/cipherboy/GitHub/cipherboy/scap-security-guide /usr/bin/python3 /home/cipherboy/GitHub/cipherboy/scap-security-guide/build-scripts/unselect_empty_xccdf_groups.py --input /home/cipherboy/GitHub/cipherboy/scap-security-guide/build/ssg-ocp4-xccdf.xml --output /home/cipherboy/GitHub/cipherboy/scap-security-guide/build/ssg-ocp4-xccdf.xml && /usr/bin/oscap xccdf resolve -o /home/cipherboy/GitHub/cipherboy/scap-security-guide/build/ssg-ocp4-xccdf.xml /home/cipherboy/GitHub/cipherboy/scap-security-guide/build/ssg-ocp4-xccdf.xml && /usr/bin/xmllint --nsclean --format --output /home/cipherboy/GitHub/cipherboy/scap-security-guide/build/ssg-ocp4-xccdf.xml /home/cipherboy/GitHub/cipherboy/scap-security-guide/build/ssg-ocp4-xccdf.xml
File '/home/cipherboy/GitHub/cipherboy/scap-security-guide/build/ssg-ocp4-xccdf.xml' line 260: Element '{http://checklists.nist.gov/xccdf/1.1}platform': The attribute 'idref' is required but missing.
File '/home/cipherboy/GitHub/cipherboy/scap-security-guide/build/ssg-ocp4-xccdf.xml' line 260: Element '{http://checklists.nist.gov/xccdf/1.1}platform': Character content is not allowed, because the content type is empty.
File '/home/cipherboy/GitHub/cipherboy/scap-security-guide/build/ssg-ocp4-xccdf.xml' line 401: Element '{http://checklists.nist.gov/xccdf/1.1}platform': The attribute 'idref' is required but missing.
File '/home/cipherboy/GitHub/cipherboy/scap-security-guide/build/ssg-ocp4-xccdf.xml' line 401: Element '{http://checklists.nist.gov/xccdf/1.1}platform': Character content is not allowed, because the content type is empty.
File '/home/cipherboy/GitHub/cipherboy/scap-security-guide/build/ssg-ocp4-xccdf.xml' line 521: Element '{http://checklists.nist.gov/xccdf/1.1}platform': The attribute 'idref' is required but missing.
File '/home/cipherboy/GitHub/cipherboy/scap-security-guide/build/ssg-ocp4-xccdf.xml' line 521: Element '{http://checklists.nist.gov/xccdf/1.1}platform': Character content is not allowed, because the content type is empty.
File '/home/cipherboy/GitHub/cipherboy/scap-security-guide/build/ssg-ocp4-xccdf.xml' line 586: Element '{http://checklists.nist.gov/xccdf/1.1}platform': The attribute 'idref' is required but missing.
File '/home/cipherboy/GitHub/cipherboy/scap-security-guide/build/ssg-ocp4-xccdf.xml' line 586: Element '{http://checklists.nist.gov/xccdf/1.1}platform': Character content is not allowed, because the content type is empty.
File '/home/cipherboy/GitHub/cipherboy/scap-security-guide/build/ssg-ocp4-xccdf.xml' line 657: Element '{http://checklists.nist.gov/xccdf/1.1}platform': The attribute 'idref' is required but missing.
File '/home/cipherboy/GitHub/cipherboy/scap-security-guide/build/ssg-ocp4-xccdf.xml' line 657: Element '{http://checklists.nist.gov/xccdf/1.1}platform': Character content is not allowed, because the content type is empty.
OpenSCAP Error: Invalid XCCDF Checklist (1.1) content in /home/cipherboy/GitHub/cipherboy/scap-security-guide/build/ssg-ocp4-xccdf.xml. [../../../src/source/oscap_source.c:342]
```

This doesn't appear to happen on any other products. 

#### SCAP Security Guide Version:

commit 3c725d836b3d67ff7cc68d59d50844a1507db420 (upstream/master, origin/master, origin/HEAD, master)

#### Operating System Version:

```
VERSION="20.10 (Groovy Gorilla)"
```

```
ii  libopenscap-dev                            1.2.17-0.1ubuntu1.1                                 amd64        Set of libraries enabling integration of the SCAP line of standards
ii  libopenscap8                               1.2.17-0.1ubuntu1.1                                 amd64        Set of libraries enabling integration of the SCAP line of standards
ii  python3-openscap                           1.2.17-0.1ubuntu1.1                                 amd64        Set of libraries enabling integration of the SCAP line of standards
```

#### Steps to Reproduce:

1. Attempt to build OpenSCAP in default configuration with all products on Ubuntu host.
2.
3.
4.

#### Actual Results:

Build fails; see above.

#### Expected Results:

Build succeeds.

#### Additional Information/Debugging Steps:

During configuration I see:

```
-- Scanning for dependencies of ocp4 fixes (bash, ansible, puppet, anaconda, ignition and kubernetes)...
-- Won't validate ocp4, as it requires the OpenSCAP scanner that is capable of the validation.
-- Won't validate ocp4, as it requires the OpenSCAP scanner that is capable of the validation.
-- Won't validate ocp4, as it requires the OpenSCAP scanner that is capable of the validation.
-- Won't validate ocp4, as it requires the OpenSCAP scanner that is capable of the validation.
```

Should we disable OCP4 altogether when too old of an oscap library is present?

**Comment by ggbecker** [comment] 2021-04-06 15:49
> 
> Should we disable OCP4 altogether when too old of an oscap library is present?

That's most likely the case. OCP4 contains non-standard (in progress https://github.com/OVAL-Community/OVAL/pull/90) OVAL content which I think is not supported by vanilla OpenSCAP1.2

**Comment by cipherboy** [comment] 2021-04-06 16:16
Thanks @ggbecker. I've filed #6799 for it. :)

**Comment by jan-cerny** [comment] 2021-04-07 07:57
> That's most likely the case. OCP4 contains non-standard (in progress OVAL-Community/OVAL#90) OVAL content which I think is not supported by vanilla OpenSCAP1.2

I think that it was a different problem. The problem was that older versions of OpenSCAP didn't contain OVAL yamlfilecontent_test in OpenSCAP's embeded XML schema so the XML schema validation returned an error. This is handled by `define_validate_product` in `cmake/SSGCommon.cmake`.

But, the error message that @cipherboy has posted here isn't about OVAL but about invalid XCCDF. Specifically, it reports invalid `<platform>` element in `build/ssg-ocp4-xccdf.xml`.

When I build OCP4 on Fedora,  in `build/ssg-ocp4-xccdf.xml` around line 260 it looks this way: `<platform idref="cpe:/o:redhat:openshift_container_platform_node:4"/>` but when I build on Ubuntu it looks like: `<xccdf-1.1:platform>cpe:/o:redhat:openshift_container_platform_node:4</xccdf-1.1:platform>`

I think that probably it's caused by wrong serialization of the `platform` element in oscap and I think that probably it's fixed by https://github.com/OpenSCAP/openscap/pull/1609. I haven't verified this, though.

**Comment by yuumasato** [comment] 2021-04-07 08:09
> When I build OCP4 on Fedora, in `build/ssg-ocp4-xccdf.xml` around line 260 it looks this way: `<platform idref="cpe:/o:redhat:openshift_container_platform_node:4"/>` but when I build on Ubuntu it looks like: `<xccdf-1.1:platform>cpe:/o:redhat:openshift_container_platform_node:4</xccdf-1.1:platform>`
> 
> I think that probably it's caused by wrong serialization of the `platform` element in oscap and I think that probably it's fixed by [OpenSCAP/openscap#1609](https://github.com/OpenSCAP/openscap/pull/1609). I haven't verified this, though.

Yes! The linked PR is responsible for the change in Profile `<xccdf-1.2:platform>` element, which was being exported incorrectly.

**Comment by jan-cerny** [comment] 2021-04-07 08:27
So this PR is a part of 1.3.4 so probably you need OpenSCAP 1.3.4 for building OCP4. But what about the OVAL schema validation? Is 1.3.4 sufficient or does he need 1.3.5 to build OCP4 because of the recent schema changes? @evgenyz

**Comment by evgenyz** [comment] 2021-04-07 08:32
It's better to wait for 1.3.5 (coming soon).

**Comment by evgenyz** [comment] 2021-04-07 08:32
1.3.4 we ship in F and RH are heavily patched.

**Closed** 2021-04-12 11:39 UTC
Labels: Infrastructure, OpenShift, Ubuntu
