### ISSUE TITLE
accounts_password_pam_dcredit: Test scenario fails to prepare on RHEL7

### ISSUE THREAD

**Issue by yuumasato** [ComplianceAsCode/content#9774] opened 2022-11-07 13:44 UTC
#### Description of problem:
When testing rule `accounts_password_pam_dcredit`, test scenario `wrong_value_directory.fail.sh` fails to prepare.

#### Operating System Version:
RHEL-7

#### Steps to Reproduce:

1. `python3 tests/test_suite.py rule --libvirt qemu:///session rhel79 --datastream build/ssg-rhel7-ds.xml accounts_password_pam_dcredit`

#### Actual Results:
```
INFO - xccdf_org.ssgproject.content_rule_accounts_password_pam_dcredit
ERROR - Rule 'accounts_password_pam_dcredit' test setup script 'wrong_value_directory.fail.sh' failed with exit code 1
ERROR - Environment failed to prepare, skipping test
```

#### Expected Results:
Test scenario is tested, or skipped, no errors.

**Comment by comps** [comment] 2022-11-16 14:09
For more test outputs and a possible cause, see #9836 (marked as duplicate of this one).

**Closed** 2022-11-23 16:13 UTC
Labels: productization-issue, RHEL7
