### ISSUE TITLE
DISA RHEL 7 STIG FIPS Rules incorrectly applied to virtual machines

### ISSUE THREAD

**Issue by Smithe2413** [ComplianceAsCode/content#5048] opened 2019-12-03 15:33 UTC
#### Description of problem:
Virtual Machines (ec2 instances in this case) have the variable `ansible_virtualization_role` set to `guest` by default. This causes the Ansible Role to skip all of the FIPS enabling tasks. 

#### SCAP Security Guide Version:
Utilizing the RedHatOfficial role
https://github.com/RedHatOfficial/ansible-role-rhel7-stig

#### Operating System Version:
Red Hat Enterprise Linux Server release 7.7 (Maipo)
3.10.0-957.21.2.el7.x86_64

#### Steps to Reproduce:

1. Create VM or EC2 instance
2. Run the STIG Role
3. Observe the FIPS tasks are skipped. 
4.

#### Actual Results:
FIPS tasks are skipped and FIPS is not enabled

#### Expected Results:
FIPS tasks run and FIPS is correctly enabled for VMs.

**Comment by Smithe2413** [comment] 2019-12-03 18:06
Also it is worth noting I removed the first "half" of the `when` statement for all the FIPS related tasks and re-ran the role. The FIPS controls were correctly applied. See below example. 

```
- name: install dracut-fips
  package:
    name: dracut-fips
    state: present
  when:
  - ansible_virtualization_role  != "docker"
  - high_complexity | bool
  - restrict_strategy | bool
  - reboot_required | bool
  - high_severity | bool
  - grub2_enable_fips_mode | bool
  - medium_disruption | bool
  tags:
  - grub2_enable_fips_mode
  - high_severity
  - restrict_strategy
  - high_complexity
  - medium_disruption
  - reboot_required
  - CCE-80359-3
  - NIST-800-53-IA-5
  - NIST-800-53-SC-13
  - NIST-800-53-AC-17(a)
  - NIST-800-53-AC-17(2)
  - NIST-800-53-IA-7
  - NIST-800-171-3.13.8
  - NIST-800-171-3.13.11
  - CJIS-5.10.1.2
  - DISA-STIG-RHEL-07-021350
```

**Comment by yuumasato** [comment] 2019-12-06 12:38
@Smithe2413 Could also you tell us the value of `ansible_virtualization_type` in the VMs you are using?

**Comment by Smithe2413** [comment] 2019-12-06 12:39
In my case, I was using AWS EC2 instances, Ansible facts set `ansible_virtualization_type` to `guest`

**Comment by yuumasato** [comment] 2019-12-06 13:01
>  Ansible facts set `ansible_virtualization_type` to `guest`

I'm puzzled how `ansible_virtualization_role != "guest" or ansible_virtualization_type != "docker"` evaluates to false

**Comment by Smithe2413** [comment] 2019-12-06 16:46
@yuumasato It's my understanding that
 ```
when: 
  - ansible_virtualization_role != "guest" or ansible_virtualization_type != "docker"` 
```
means that this task will only execute when `ansible_virtualization_role` **does not** equal `docker` or `guest`. Since VMs get the value `guest` assigned to them, the FIPS tasks do not run against those hosts.

**Comment by matejak** [comment] 2019-12-09 13:58
> ... task will only execute when ansible_virtualization_role does not equal docker or guest.

The logical OR means that if any of those conditions is met, the task is supposed to be executed. So even if `ansible_virtualization_role` is `guest`, the task may still be executed - if `ansible_virtualization_type` is not `docker`.

In other words, removing a part of `or` makes the condition less likely to pass, so it doesn't make sense that it helped. It may either indicate a bug in Ansible, or the change was caused by something else.
The task has a lot of other conditions under `when`, and all individual sub-items are required to evaluate to true in order for the task to be executed. Could it be that it was in fact some other item that prevented the task execution?

**Comment by matejak** [comment] 2020-05-15 14:50
I have managed to get hands on an Amazon instance, and I got these results:

When checking out the system facts, I have logged in and executed

```
ansible -m setup -c localhost localhost | grep virt
```

What I got on that particular Amazon instance was
```
...
"ansible_virtualization_role": "guest",
"ansible_virtualization_type": "xen",
```

which means that the condition

```
when:
 - ansible_virtualization_role != "guest" or ansible_virtualization_type != "docker"` 
```

would become

```
when:
 - False or True
```

which is True, i.e. the task execution is not blocked by particular condition.

I trust you that it was skipped, but that could have been caused by another conditions in the `when:` section. I don't know why do we have them there. My understanding is that if  we have `  - high_complexity | bool` in the `when` block, it will block the execution if `high_complexity` happens to be False. Tasks are tagged with those attribute (e.g. with the complexity, strategy, severity etc.), so having those under `when:` seems to be redundant.

**Comment by carlosmmatos** [comment] 2020-07-20 17:14
Upon looking into this - there are a couple of things that need to be addressed:

- How should we best address checking for containers? 
    - I submitted an upstream [Ansible PR](https://github.com/ansible/ansible/pull/70697/files) to help address this issue, but the bottom line is that this logic won't be implemented until 2.11+, if it gets accepted.
    - We need to implement some logic now to help determine whether the target system is running in a container. Again, in RHEL we are stuck with an older version of Ansible that pretty much just tells you whether this is a docker container or not... it doesn't check for podman or others yet as it will down the pipeline of Ansible.

With that - here are some suggestions that I would like to open up for discussion:
> **NOTE:** Please notice that in my when clauses, I'm not checking for `ansible_virtualization_role != guest` as this seems self implied when explicitly declaring checks against `ansible_virtualization_type`. However please correct me if that assumption is incorrect.

- We can check for the different types of containers known to upstream [Ansible](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/facts/virtual/linux.py)
```yaml
when:
  - ansible_virtualization_type != "lxc"
  - ansible_virtualization_type != "docker"
  - ansible_virtualization_type != "podman"
  - ansible_virtualization_type != "container"
  - ansible_virtualization_type != "openvz"
```
Which is quite descriptive, but nasty to look at.

- Or we can set a variable (I'm not sure the best way to do this) somewhere with:
```yaml
container_list:
  - "lxc"
  - "docker"
  - "podman"
  - "container"
  - "openvz"

...
...

when: ansible_virtualization_type not in container_list
```
This is cleaner to look at it.

- Should we be trying to determine the type of container being used (as it's already implemented in future Ansible releases)?

**Comment by isimluk** [comment] 2020-07-21 15:48
:+1: for `container_list` idea!

**Comment by carlosmmatos** [comment] 2020-07-21 19:20
@yuumasato What are your thoughts on going about updating `build_remediations.py` to update then additional when clause we currently have there, to be more specific that we are trying to ensure they don't run in a container env?

**Comment by yuumasato** [comment] 2020-07-22 13:27
The variable approach seems good, I think it will make maintenance easier.
AFAIK, we don't have a common place where variables are sourced from.
So, I think `build_remediations.py` would have to add the variable to every Ansible remediation snippet it touches, unless some other redesign happens.

About `ansible_virtualization_role != guest`, discussing with @matejak . It seems to be there to avoid matching a system which is the `host` of a container engine. Something like a docker host.
But from your PR I don't see 'role: host type: docker` as a possibility, even for other container types. Maybe this is not an issue at all?

Note: I still puzzled by the original issue, per this https://github.com/ComplianceAsCode/content/issues/5048#issuecomment-629277878, the FIPS tasks should be applied.

**Comment by carlosmmatos** [comment] 2020-07-22 19:18
I agree that there was something else that may have caused the original issue that the OP had, but it still sheds light on how we check for certain conditions (ie, not in a container env). 

You are correct that if you take a look at the upstream pr, there seems to be no possibility of confusing `ansible_virtualziation_role` and `type` with docker/host combo - which is why I don't see the point of having that check, seems redundant and implied. But if @matejak has an example output, we can definitely come back to this.

I'll have to think more about how to implement the variable approach, I was hoping we had some mechanism for that already in place, but it sounds like that's not the case currently. We can also stick the multiple when clause, or instead of having:
```yaml
when:
  - ansible_virtualization_type != "lxc"
  - ansible_virtualization_type != "docker"
  - ansible_virtualization_type != "podman"
  - ansible_virtualization_type != "container"
  - ansible_virtualization_type != "openvz"
```
maybe we just one line it:
``` yaml
when:
  - ansible_virtualization_type not in ["lxc", "docker", "podman", "container", "openvz"]
```
Thoughts?

**Comment by redhatrises** [comment] 2020-07-22 19:32
The container_list idea is more the route that we should take as it can be placed in a var which works for playbooks and roles. That way when the 'container' fact makes its way downstream. Should be an easy change.

**Comment by matejak** [comment] 2020-07-23 14:05
The problem with the `ansible_virtualization_role` that can be `guest` or `host` is that its behavior is not documented. If I am inside a container, then `role` is `guest`, and `type` is `docker`. If I am on my desktop, `role` is `host`, and `type` is `kvm`. However, `role` being `host` and `type=podman` would be correct as well, as I run `podman` containers on my machine, and if I happen to run the `docker` service, I am also a `docker` and a `host`.
Therefore, I very strongly suggest that we keep the `role=guest` check, as there is no evidence that it causes problems, and it won't break if Ansible slightly changes its behavior, and it starts to acknowledge other host types than `kvm` `host`. You can find a lot of PRs that fixes code that relied on assumptions that ceased to hold one day (my recent favourite is #5054)

**Comment by yuumasato** [comment] 2020-08-11 08:40
@carlosmmatos How do you feel about keeping the check for `role=guest`?
At least until your PR to Ansible is merged and available.

**Comment by carlosmmatos** [comment] 2020-08-12 17:16
@yuumasato I guess I'm still not convinced it's needed.. here's my rationale:

If I'm adding a when clause to make sure we are not a container - then do I really care if my role is host or guest? In fact, I think the only possible options for virtualization_role we have with as of 2.9.12 are `'guest', 'host', 'NA', and something called 'LPAR'`.

The meat of what we are testing against is in `virtualization_type`, that is why I don't think we need to have role. Does that make sense? 

Also - it is very possible that current implementations of Ansible won't have the latest capabilities in the linux.py module_utils facts - so there is a great chance that we may miss something (ie, running a podman container). @redhatrises had a PR that had a check for podman containers that was closed due to inactivity, but maybe we may need to consider this again.

**Comment by carlosmmatos** [comment] 2020-08-12 19:02
ok - so this seems to just be a limitation to the linux.py on current Ansible versions.. btw my upstream PR got messed up because they updated the file again. It seems like they are going to be deprecating `ansible_virtualization_role|type` in future releases in favor of `ansible_virtualization_tech_guest|host`. But my additions should still be relevant.

Here is the output using latest dev branch upstream - running from a podman container on physical host:
```yaml
$ ansible localhost -m setup
...
        "ansible_virtualization_role": "guest",
        "ansible_virtualization_tech_guest": [
            "podman",
            "container"
        ],
        "ansible_virtualization_tech_host": [
            "kvm"
        ],
        "ansible_virtualization_type": "podman",
        "gather_subset": [
            "all"
        ],
...
```

So same setup - but instead of being `role=host and type=kvm`, it's now `role=guest and type=podman` .. so how should we approach this? @yuumasato @matejak

**Closed** 2020-08-19 22:41 UTC
