### ISSUE TITLE
Test scenario for grub2_disable_interactive_boot fails

### ISSUE THREAD

**Issue by yuumasato** [ComplianceAsCode/content#9177] opened 2022-07-19 09:56 UTC
#### Description of problem:
Test scenario `enabled_interactive_boot_empty_boolean.fail.sh` from rule `grub2_disable_interactive_boot` fails on RHEL-7

#### SCAP Security Guide Version:
8c07d73

#### Operating System Version:
RHEL-7

#### Steps to Reproduce:

1. python3 tests/test_suite.py rule  --libvirt qemu:///session rhel79 --datastream build/ssg-rhel7-ds.xml grub2_disable_interactive_boot
2.
3.
4.

#### Actual Results:
```
INFO - xccdf_org.ssgproject.content_rule_grub2_disable_interactive_boot
INFO - Script disabled_interactive_boot.pass.sh using profile (all) OK
INFO - Script disabled_recovery_boot.pass.sh using profile (all) OK
INFO - Script enabled_interactive_boot.fail.sh using profile (all) OK
INFO - Script enabled_interactive_boot_empty_boolean.fail.sh using profile (all) OK
ERROR - Rule evaluation resulted in fail, instead of expected pass during final stage 
ERROR - The check after remediation failed for rule 'xccdf_org.ssgproject.content_rule_grub2_disable_interactive_boot'.
INFO - Script enabled_recovery_boot.fail.sh using profile (all) OK
```

#### Expected Results:
All test scenarios get the expected results.

**Comment by mildas** [comment] 2022-07-19 10:56
Duplicate of https://github.com/ComplianceAsCode/content/issues/9140

**Closed by mildas** 2022-07-19 10:56 UTC
Labels: productization-issue
