### ISSUE TITLE
Ubuntu AIDE

### ISSUE THREAD

**Issue by modem7** [ComplianceAsCode/content#10422] opened 2023-04-04 10:45 UTC
#### Description of problem:
```bash
Running aide --init...
WARNING: /etc/aide/aide.conf:194: Using 'database' is DEPRECATED. Update your config and use 'database_in' instead (line: 'database=file:/var/lib/aide/aide.db')
```

#### SCAP Security Guide Version:
http://static.open-scap.org/ssg-guides/ssg-ubuntu2204-guide-cis_level1_server.html#xccdf_org.ssgproject.content_rule_aide_build_database

#### Operating System Version:
Ubuntu 22.04

#### Steps to Reproduce:

1. oscap xccdf eval --profile=xccdf_org.ssgproject.content_profile_cis_level1_server --results-arf xccdfarf.xml --report xccreport.html scap-security-guide-0.1.66/ssg-ubuntu2204-ds.xml
2. oscap xccdf generate fix --profile=xccdf_org.ssgproject.content_profile_cis_level1_server xccdfarf.xml > fix.sh
3. bash ./fix.sh

#### Actual Results:
```bash
Remediating rule 3/251: 'xccdf_org.ssgproject.content_rule_aide_build_database'
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
aide is already the newest version (0.17.4-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Running aide --init...
WARNING: /etc/aide/aide.conf:194: Using 'database' is DEPRECATED. Update your config and use 'database_in' instead (line: 'database=file:/var/lib/aide/aide.db')
```

#### Expected Results:
For aide --init to run properly

#### Additional Troubleshooting:
```bash
# Fix db path in the config file, if necessary
if ! grep -q '^database_in=file:' ${AIDE_CONFIG}; then
    # replace_or_append gets confused by 'database_in=file' as a key, so should not be used.
    #replace_or_append "${AIDE_CONFIG}" '^database_in=file' "${DEFAULT_DB_PATH}" '@CCENUM@' '%s:%s'
    echo "database_in=file:${DEFAULT_DB_PATH}" >> ${AIDE_CONFIG}
fi
```

Seems to fix

**Comment by dodys** [comment] 2023-04-04 11:51
I'm closing this as a duplicate of #8838

**Closed by dodys** 2023-04-04 11:51 UTC
Labels: Ubuntu, CIS
