### ISSUE TITLE
SSG Test Suite doesn't run Ansible remediations

### ISSUE THREAD

**Issue by jan-cerny** [ComplianceAsCode/content#3730] opened 2019-02-01 14:04 UTC
#### Description of problem:
It is not possible to test Ansible remediations using SSG Test Suite on Fedora 29 target VMs. This happens also with RHEL8 targets.

Ansible requires Python to run. As a default, it uses `/usr/bin/python`. However, on Fedora 29, there is no  `/usr/bin/python`. You have to specify `ansible_python_interpreter=/usr/bin/python3` in your **inventory** in order to apply Ansible playbooks to the system.

#### SCAP Security Guide Version:
current upstream head as of 1st February 2019

#### Operating System Version:
host: all
guest: Fedora 29

#### Steps to Reproduce:

1. `./test_suite.py rule --debug --remediate-using ansible --libvirt  qemu:///system test-suite-fedora --datastream ../build/ssg-fedora-ds.xml --xccdf-id scap_org.open-scap_cref_ssg-fedora-xccdf-1.2.xml accounts_passwords_pam_faillock_deny_root`
2.
3.
4.

#### Actual Results:

Ansible fails to apply remediations playbooks to the target VM, because it cannot find Python interpreter. See the fatal error below.

Contents of `xccdf_org.ssgproject.content_rule_accounts_passwords_pam_faillock_deny_root-missing-default-die-pam_faillock.fail.sh-remediation.verbose.log` :

```
Stdout of "ansible-playbook -i 192.168.122.108, -uroot /home/jcerny/scap-security-guide/tests/logs/rule-custom-2019-02-01-1411/xccdf_org.ssgproject.content_rule_accounts_passwords_pam_faillock_deny_root.yml":   ____________
< PLAY [all] >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||  

 ________________________
< TASK [Gathering Facts] >
 ------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||  

fatal: [192.168.122.108]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 192.168.122.108 closed.\r\n", "module_stdout": "/bin/sh: /usr/bin/python: No such file or directory\r\n", "msg":    "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error", "rc": 127} 
>---to retry, use: --limit @/home/jcerny/scap-security-guide/tests/logs/rule-custom-2019-02-01-1411/xccdf_org.ssgproject.content_rule_accounts_passwords_pam_faillock_deny_root.retry
 ____________
< PLAY RECAP >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||  

192.168.122.108            : ok=0    changed=0    unreachable=0    failed=1   
```

#### Expected Results:
Ansible applies the remediation playbooks on the target VM during rule testing.

#### Addition Information/Debugging Steps:
We probably need to find a way how to set `ansible_python_interpreter` based on the OS installed in the target VM.

**Comment by matejak** [comment] 2019-02-04 09:48
This is not a test suite bug - it is enough to make sure that `/usr/bin/python` is available, which is easy on Fedora 29 - just install `python2` that depends on `python-unversioned-command`.
I was not able to reproduce this on a Fedora container.

**Comment by jan-cerny** [comment] 2019-02-04 10:03
@matejak That's a great workaround! Thank you very much.

However, I have 2 problems:
1. This package isn't in our kickstart.
2. On RHEL 8, no package provides `/usr/bin/python`.

**Comment by matejak** [comment] 2019-02-04 12:58
So I did some investigation into RHEL8 and you are right - for the beta release, RedHat recommends to set the `ansible_python_interpreter` to appropriate versions.
Personally, I would go for provisioning VMs so there is a `/usr/bin/python` symlink, this feels quite manual - Ansible should be able to figure out what Python to use.

**Comment by jan-cerny** [comment] 2019-03-06 11:39
We need to test our Ansible content on RHEL8 now.

**Comment by redhatrises** [comment] 2019-03-06 15:15
The test suite should incorporate the following for ansible playbook testing https://github.com/ansible/molecule

**Comment by matejak** [comment] 2019-03-14 11:13
This Ansible shortcoming has an issue reported: https://github.com/ansible/ansible/issues/45852

**Comment by matusmarhefka** [comment] 2022-06-02 08:15
Issue should be fixed now (tested with Fedora 35), closing.

**Closed by matusmarhefka** 2022-06-02 08:15 UTC
Labels: Test Suite
