### ISSUE TITLE
aide.conf database lookup deprecated (xccdf_org.ssgproject.content_rule_aide_build_database, Ubuntu 22.04)

### ISSUE THREAD

**Issue by drscream** [ComplianceAsCode/content#10890] opened 2023-07-21 09:52 UTC
#### Share the context

Running `oscap xccdf eval` with `xccdf_org.ssgproject.content_profile_cis_level2_server` profile in `scap-security-guide-0.1.68/ssg-ubuntu2204-ds.xml`. Based on that I've detected an issue in the regular expression or rule `xccdf_org.ssgproject.content_rule_aide_build_database` for aide.

* operating system: Ubuntu 22.04
* scap security guide: 0.1.68

#### Description of problem:

The current rule `xccdf_org.ssgproject.content_rule_aide_build_database` for the Ubuntu 22.04 operating system is not working as expected. The current check and remediation looks for `database=file:` which is deprecated and will be removed in a future version of `aide`.

#### Proposed change:

From my point of view the rule and regulation expression need to be changed from `database=file:` to `database_in=file`. It might be required to provide an extra oval file for Ubuntu >= 22.04 depends how older system require the `aide.conf` entry.

#### References:

1. https://github.com/ComplianceAsCode/content/blob/d99f9795a94274d24e459beaf3ed3cc17f6d9e92/linux_os/guide/system/software/integrity/software-integrity/aide/aide_build_database/oval/ubuntu.xml#L42
2. https://github.com/ComplianceAsCode/content/blob/d99f9795a94274d24e459beaf3ed3cc17f6d9e92/linux_os/guide/system/software/integrity/software-integrity/aide/aide_build_database/bash/ubuntu.sh#L9
3. https://manpages.ubuntu.com/manpages/lunar/en/man5/aide.conf.5.html

**Comment by dodys** [comment] 2023-07-24 09:56
Duplicate of #10858

**Closed by dodys** 2023-07-24 09:56 UTC
Labels: enhancement, Ubuntu
