### ISSUE TITLE
`platforms:` in the rule no longer works

### ISSUE THREAD

**Issue by jhrozek** [ComplianceAsCode/content#8833] opened 2022-05-25 10:42 UTC
#### Description of problem:
We have a rule [applications/openshift/api-server/api_server_api_priority_flowschema_catch_all](https://github.com/ComplianceAsCode/content/blob/master/applications/openshift/api-server/api_server_api_priority_flowschema_catch_all/rule.yml) that is supposed to run on a subset of OCP releases only. This doesn't work anymore.

The rule selects the platforms like this:
```
prodtype: ocp4


platforms:
  - ocp4.8
  - ocp4.9
  - ocp4.10
```

#### SCAP Security Guide Version:
today's master

#### Operating System Version:
OCP 4.10

#### Steps to Reproduce:

1. build the content
2. run the rule xccdf_org.ssgproject.content_rule_api_server_api_priority_flowschema_catch_all
3.
4.

#### Actual Results:
not applicable

#### Expected Results:
pass/fail

#### Additional Information/Debugging Steps:
Using git bisect, it seems like the last commit where the selection works is 9fcf5e255e6f5477515974fca266667cb73b8364 and the first one where it doesn't is 6a8bc3c7b396eb044cea32b531070ef9cc99caa9

I'm going to attach debug logs from both a good and a bad run.

**Comment by jhrozek** [comment] 2022-05-25 10:44
[notaplicable.log](https://github.com/ComplianceAsCode/content/files/8770337/notaplicable.log)
[pass.log](https://github.com/ComplianceAsCode/content/files/8770338/pass.log)

**Comment by evgenyz** [comment] 2022-05-25 11:16
It looks like the problem is with platform Id. In the rule it is `<xccdf-1.2:platform idref="#ocp4.10"/>` and the platform itself is `<xccdf-1.2:platform idref="cpe:/a:redhat:openshift_container_platform:4.10"/>`.

**Comment by evgenyz** [comment] 2022-05-25 11:18
BTW, profile references platform correctly.

**Comment by evgenyz** [comment] 2022-05-25 11:20
It looks like it has already been fixed in `cpe_applicability` branch.

**Comment by jhrozek** [comment] 2022-05-25 11:43
> It looks like it has already been fixed in `cpe_applicability` branch.

Can we backport this fix to master sooner than when this branch merged? This is breaking some rules we had already released ...

**Comment by evgenyz** [comment] 2022-05-25 12:18
> > It looks like it has already been fixed in `cpe_applicability` branch.
> 
> Can we backport this fix to master sooner than when this branch merged? This is breaking some rules we had already released 

As soon as we figure out what exactly it was.

**Comment by evgenyz** [comment] 2022-05-26 13:02
Note:
```
platforms:
  - ocp4.8 or ocp4.9 or ocp4.10
```
does work as intended.

**Comment by evgenyz** [comment] 2022-05-26 13:05
We should deprecate list-like notation.

**Comment by jhrozek** [comment] 2022-05-29 13:33
> We should deprecate list-like notation.

Fine by me!

**Comment by marcusburghardt** [comment] 2023-08-25 13:22
@evgenyz can you confirm if this issue can be closed, please?

**Comment by evgenyz** [comment] 2023-08-25 19:17
Have we deprecated / dropped the `platforms` keyword?

**Comment by evgenyz** [comment] 2023-08-27 18:45
I mean, we can close it, but the broken misleading `platforms` is how we got into this problem in the first place.

**Closed** 2023-08-28 08:56 UTC
Labels: enhancement, Infrastructure, CPE-AL
