### ISSUE TITLE
Selecting nonexisting rule in a profile silently passes

### ISSUE THREAD

**Issue by vojtapolasek** [ComplianceAsCode/content#9297] opened 2022-08-05 08:15 UTC
#### Description of problem:

When you select a rule which does not exist in the profile, the compilation goes on without errors. Of course the rule does not appear in the final profile. But I believe there should be at least a warning.

#### SCAP Security Guide Version:
master

#### Operating System Version:
FEdora

#### Steps to Reproduce:

1. Edit any profile and add some bogus rule there.
2. Build the content for the product

#### Actual Results:
Compilation finishes without any visible warning that you are selecting nonexisting rule.

#### Expected Results:
The compilation aborts.

#### Additional Information/Debugging Steps:
I made a typo in a rule name and I was wondering for half an hour why the rule just does  not appear in the profile.

**Comment by yuumasato** [comment] 2022-08-05 09:47
I believe this is a duplicate of #8870

**Closed** 2022-08-10 08:22 UTC
