### ISSUE TITLE
create-stig-overlay.py doesn't keep ruleid for stig_overlay.xml

### ISSUE THREAD

**Issue by jamescassell** [ComplianceAsCode/content#2761] opened 2018-04-17 13:12 UTC
#### Description of problem:
the script at shared/utils/create-stig-overlay.py should keep the ruleid when regenerating the stig_overlay.xml file.  It seems that the script is written to do this, but it is not working.

#### SCAP Security Guide Version:
master version of the script, 0.1.38 version of ssg xccdf passed into the script.

#### Operating System Version:
RHEL 7.4

#### Steps to Reproduce:

1. `oscap ds sds-split ssg-rhel6-ds.xml /tmp`
2. `shared/utils/create-stig-overlay.py --disa-xccdf shared/references/disa-stig-rhel7-v1r4-xccdf-manual.xml --ssg-xccdf /tmp/scap_org.open-scap_cref_ssg-rhel6-xccdf-1.2.xml -o rhel6/overlays/stig_overlay.xml`

#### Actual Results:
stig_overlay.xml generated with `ruleid="XXXX"`

#### Expected Results:
stig_overlay.xml generated with `ruleid="<relevant-ruleid>"`

#### Addition Information/Debugging Steps:
It's possible this is user error.  I've also tried passing the ssg-rhel6-ds.xml directly to the script instead of just the xccdf.  I've also tried to pass it the ssg-rhel6-ds.xml and the split-out xccdf from a local build, but the script fails because the xccdf is not an official build.

**Comment by redhatrises** [comment] 2018-04-17 13:17
@jamescassell does this work if the ssg-rhel6-xccdf.xml is used directly from a build? Script was designed to work directly from a build and xccdf xml file not from a datastream split.

**Comment by jamescassell** [comment] 2018-04-17 14:50
I was able to work around the python error by injecting the following to the ssg-rhel6-xccdf.xml generated by a local build:
```
   <version update="https://github.com/OpenSCAP/scap-security-guide/releases/latest">0.1.39</version>
+  <metadata>
+<dc:publisher xmlns:dc="http://purl.org/dc/elements/1.1/">SCAP Security Guide Project</dc:publisher>
+  </metadata>
   <model system="urn:xccdf:scoring:default"/>
```

unfortunately, the output stig_overlay.xml still had all the `ruleid=` vars replaced with `XXXX`

**Comment by jamescassell** [comment] 2018-04-17 14:50
@redhatrises does it work for you when run locally?

**Comment by jamescassell** [comment] 2019-03-20 03:29
This one works successfully today on Fedora 29; didn't try on RHEL 7.

Here is the successful incantation:
```bash
cd build
cmake ../
make -j12 rhel7-content
cd ..
PYTHONPATH=`./.pyenv.sh` utils/create-stig-overlay.py --disa-xccdf shared/references/disa-stig-rhel7-v2r2-xccdf-manual.xml --ssg-xccdf build/ssg-rhel7-xccdf.xml -o rhel7/overlays/stig_overlay.xml
```

If this file is truly supposed to be only-ever machine generated, we should stop tracking it in git and have the build system generate it at build time.  Even now, when I regenerate, the version in git is out-of-date.

Removing this file from git would obviate the problem of the xml file now being illegible and repetitive, as mentioned in the other thread.

**Comment by riskpeep** [comment] 2019-06-06 17:33
I was having a similar issue today (maybe the same one) with create-stig-overlay.py putting 'XXXX' in the rule id.

I did some looking and found that there are two cases where you get the XXXX.

First is if there is no passed ssg-xccdf, you'll get this (because there is nothing to map to.)  I don't think this is the error you're getting.

Second is if the method get_nested_stig_items in create-stig-overlay.py can't find a rule to map to it will return XXXX.  

```
owner = "disastig"
stig_ns = ["http://iase.disa.mil/stigs/os/unix-linux/Pages/index.aspx",
           "http://iase.disa.mil/stigs/os/general/Pages/index.aspx",
           "http://iase.disa.mil/stigs/app-security/app-servers/Pages/general.aspx"]
xccdf_ns = "http://checklists.nist.gov/xccdf/1.1"
dc_ns = "http://purl.org/dc/elements/1.1/"
outfile = "stig_overlay.xml"

. . .

def get_nested_stig_items(ssg_mapping, srg):
    mapped_id = "XXXX"
    for rhid, srgs in ssg_mapping.iteritems():
        for xccdfid, srglist in srgs.iteritems():
            if srg in srglist and len(srglist) > 0:
                mapped_id = xccdfid
                break

    return mapped_id
```

For me this was failing for two reasons.  The first reason was that the list of name space URLs listed in 'create-stig-overlay.py' as variable 'stig_ns' didn't match the list of name space URLs in ./shared/transforms/shared_constants.xslt.  They need to match because the ns url for 'disa-appsrguri' in shared_constants.xslt didn't match the one in create-stig-overlay.py.  That causes the reference map creation to fail in the method ssg_xccdf_stigid_mapping.  I had to change:

http://iase.disa.mil/stigs/app-security/app-servers/Pages/index.aspx
to
http://iase.disa.mil/stigs/app-security/app-servers/Pages/general.aspx

in create-stig-overlay.py.

The second reason the mapping was failing is because the check in get_nested_stig_items wants to make sure that the rule maps to an SRG item, but also that the list of SRG items has more than 1 item.  SO if you only map to one SRG, then you get XXXX.  You can see that in the snippet above.  I changed the 1 to a 0 in the check line.

**Comment by ggbecker** [comment] 2020-10-01 15:00
Cannot reproduce with [master](9704d00fff8d2653eaa6ab9dda95543b87a1b23e) anymore. Closing this issue. Feel free to reopen it if you still have problems.

**Closed by ggbecker** 2020-10-01 15:00 UTC
Labels: Python, backlog, bugfix
