### ISSUE TITLE
Templated test scenarios handling is wrong

### ISSUE THREAD

**Issue by matejak** [ComplianceAsCode/content#8772] opened 2022-05-16 12:53 UTC
#### Description of problem:

The test framework allows to skip templated test scenarios, as it may be often the case that similar rules are tested alongside, and executing the same test scenarios again and again provides no value. However, there are following problems coming from the implementation - skipping of templated test scenarios is handled on the rule level. So if a rule is templated, then the first templated rule gets all its scenarios executed, and all other templated rules (regardless of the template type) are skipped.

- Custom test scenarios of templated rules are not executed.
- If more template types are encountered, they are treated as one type, so some templated test scenarios will be skipped without any real reason.

#### Actual Results:

The test suite tends to skip too many test scenarios.

#### Expected Results:

The test suite executes each test scenario only once per test run. Custom test scenarios are executed without any limitations, and test scenarios of different templates are distinguished appropriately.

See the filtering code: https://github.com/ComplianceAsCode/content/blob/869e6b5c0fa1600f13d1513a8a603858afab6600/tests/ssg_test_suite/rule.py#L215

**Comment by jan-cerny** [comment] 2022-07-29 12:00
@matejak @mildas @matusmarhefka  I think that I can't reproduce this problem with the current upstream master (as of HEAD 6c9fcf1b9604d71025697f41b50664a980ba6b14). 

I executed tests in rule mode for rules package_tmux_installed, package_libselinux_installed, file_owner_etc_group and file_groupowner_etc_group on a RHEL 9 back end.

```
[jcerny@thinkpad scap-security-guide{master}]$ python3 tests/automatus.py rule --remediate-using ansible --libvirt qemu:///system ssgts_rhel9 package_tmux_installed package_libselinux_installed file_owner_etc_group file_groupowner_etc_group
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - Logging into /home/jcerny/work/git/scap-security-guide/logs/rule-custom-2022-07-29-1348/test_suite.log
INFO - xccdf_org.ssgproject.content_rule_package_tmux_installed
INFO - Script package-installed.pass.sh using profile (all) OK
INFO - Script package-installed-removed.fail.sh using profile (all) OK
INFO - Script package-removed.fail.sh using profile (all) OK
INFO - xccdf_org.ssgproject.content_rule_file_groupowner_etc_group
INFO - Script incorrect_groupowner.fail.sh using profile (all) OK
INFO - Script missing_file_test.pass.sh using profile (all) OK
INFO - Script correct_groupowner.pass.sh using profile (all) OK
INFO - xccdf_org.ssgproject.content_rule_file_owner_etc_group
INFO - Script incorrect_owner.fail.sh using profile (all) OK
INFO - Script correct_owner.pass.sh using profile (all) OK
INFO - Script missing_file_test.pass.sh using profile (all) OK
INFO - xccdf_org.ssgproject.content_rule_package_libselinux_installed
INFO - Script custom-package-removed.fail.sh using profile (all) OK

```
* The custom (local) test scenario `custom-package-removed.fail.sh ` for rule `package_libselinux_installed`, which uses the package_installed template, has been executed even if templated tests for the package_installed template have been executed before, when the package_tmux_installed was tested. So I think it follows the expected behavior.

* It tests rules `file_groupowner_etc_group` which uses the `file_groupowner` template and `file_owner_etc_group` which uses the `file_owner` template. So we have 2 different templates, both contain 3 test scenarios, in both of the templates there is a test scenario with the file name `missing_file_test.pass.sh`. In this Automatus run, all the test scenarios for both templates have been tested, notice the output contain a test scenario missing_file_test.pass.sh under both rules. So I think it follows the expected behavior.

@matejak @mildas @matusmarhefka  Do you think that we are fixed and we can close this issue?

**Comment by matusmarhefka** [comment] 2022-08-02 11:09
@jan-cerny Yes, I can confirm your results with the latest `master` branch, test suite behavior is correct so the reported issue is fixed.

**Closed by matusmarhefka** 2022-08-02 11:09 UTC
Labels: Infrastructure, Test Suite
